bookmytrips/urls.py
from django.conf.urls import url, handler404, handler500
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('mainapp.urls')),
]

handler404 = 'mainapp.views.error_404_view'
handler500 = 'mainapp.views.error_500_view'

mainapp/urls.py
from django.urls import path
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    # path('search/', views.search, name='search'),
    path('countries/<int:id>/', views.tour_packages, name='tourselect'),
    path('profile/', views.profile, name = 'profile'),
    # path('profile/update/', views.update_profile, name = 'update'),
    path('tour-id/<int:tour_id>', views.select_tour, name = 'select_tour'),
    path('add-to-cart/<int:tour_id>', views.add_to_cart, name = 'add_to_cart'),
    path('cart-items/', views.cart_items, name = 'cart_items'),
    # path('checkout/<int:cart_id>', views.checkout, name = 'checkout'),
    path('handlerequest', views.handlerequest, name = 'handlerequest'),
    path('tour-detail/<int:order_id>', views.booked_tours_detail, name = 'booked_tours_detail')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+= (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

mainapp/models.py
from django.db import models
from django.conf import settings
from django.forms import ModelForm
from datetime import date
from django_resized import ResizedImageField


User = settings.AUTH_USER_MODEL
gender_choices = (('male', 'male'), ('female', 'female'))


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'profile_image/user_{0}/{1}'.format(instance.user.id, filename)

DEFAULT = 'profile_image/default/default.png'

class Country(models.Model):
    name = models.CharField(max_length=100)
    image = models.CharField(max_length=500, null=True, blank=True)
    country_description = models.TextField(null=True, blank=True)
    def __str__(self):
        return f'{self.name}'


class Tour(models.Model):
    # country = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    place = models.CharField(max_length=100)
    tour_duration = models.CharField(max_length=100)
    title = models.TextField()
    image = models.CharField(max_length=500, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    cost = models.IntegerField(null=True, blank=True)
    amenities = models.TextField(null=True, blank=True)
    reasons_to_choose = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.country} {self.place}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # avatar = models.CharField(max_length=100)
    avatar = ResizedImageField( upload_to=user_directory_path, default=DEFAULT)
    dob = models.DateField()
    gender = models.CharField(choices=gender_choices, max_length=10)
    description = models.TextField()

    def __str__(self):
        return f'{self.user}'

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    tour = models.ForeignKey(Tour, on_delete = models.CASCADE)
    head_count = models.IntegerField(default = 0)
    tour_date = models.DateField()
    booking_date = models.DateField(("Date"), default=date.today)
    sell_status = models.BooleanField(default=False)
    total_cost = models.IntegerField(default=0)

    @property
    def total_amount(self):
        self.total_cost = self.head_count * self.tour.cost
        return self.total_cost

    

# import datetime

# class MyForm(forms.Form):
#     date = forms.DateField(...)

#     def clean_date(self):
#         date = self.cleaned_data['date']
#         if date < datetime.date.today():
#             raise forms.ValidationError("The date cannot be in the past!")
#         return date

mainapp/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User

class DateInput(forms.DateInput):
    input_type = 'date'

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ( 'dob', 'gender','description', 'avatar')
        widgets = {
            'dob': DateInput(),
            'description': forms.Textarea(attrs={'placeholder': 'Write some thing about you'})
        }


class FindDestinationForm(forms.Form):
    place = forms.CharField(label='', widget=forms.TextInput)

    def __init__(self, *args, **kwargs):
        super(FindDestinationForm, self).__init__(*args, **kwargs)
        self.fields['place'].widget.attrs.update({'class' : 'col-sm-10 col-form-label', 'placeholder': 'Where ?'})

mainapp/views.py
from django.http import JsonResponse, HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.conf import settings
from django.db.models import Count
from .forms import FindDestinationForm, UserForm, ProfileForm
from decouple import config
import os
from elasticsearch import Elasticsearch
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import Tour, Cart, Profile, Country
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from PayTm import Checksum
from django.core.mail import send_mail


Test_Merchant_ID = config('Test_Merchant_ID')
Test_Merchant_Key = config('Test_Merchant_Key')
User = get_user_model()
ELASTIC_URL = config('ELASTICSEARCH_URL')
es = Elasticsearch(ELASTIC_URL)


def error_404_view(request, exception):
    return render(request,'error_404.html')

def error_500_view(request):
    return render(request,'error_500.html')


def index(request):
    form = FindDestinationForm()
    countries = Country.objects.values()
    popular_tours = Tour.objects.values().filter(country__id=7)
        
    if request.method == 'POST':
        form = FindDestinationForm(request.POST)
        tours = Tour.objects.values()
        i = 1
        for tour in tours:
            es.index(index='tour', doc_type ='tour', id=i, body=tour)
            i += 1
        if form.is_valid():
            place = form.cleaned_data['place']
            search = es.search(index='tour', body={'query': {'multi_match': {'query': place, 'fields': ['*']}}})
            search_result = []
            for result in search['hits']['hits']:
                search_result.append(result['_source'])
        return render(request, 'index.html', {'form': form, 'countries': countries, 'search':search_result, 'popular_tours': popular_tours})
    return render(request, 'index.html', {'form': form, 'countries': countries, 'popular_tours': popular_tours})


def tour_packages(request, id):
    form = FindDestinationForm()
    tours = Tour.objects.filter(country__id=id)
    if tours:
        country = tours[0].country.name
    else:
        country = Country.objects.values('name').filter(id=id)[0]['name']

    if request.method == 'POST':
        form = FindDestinationForm(request.POST)
        i = 1
        packages = Tour.objects.values().filter(country=id)
        for package in packages:
            es.index(index=country.lower(), id=i, body=package)
            i += 1
        if form.is_valid():
            place = form.cleaned_data['place']
            search = es.search(index=country.lower(), body={'query': {'multi_match': {'query': place, 'fields': ['*']}}})
            search_result = []
            for result in search['hits']['hits']:   
                search_result.append(result['_source'])
        return render(request, 'tourpage.html', {'tours': tours, 'country': country, 'form': form, 'search':search_result})
    return render(request, 'tourpage.html', {'tours': tours, 'country':country, 'form': form})

@login_required
def profile(request):
    username = request.user.username
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)
    user_obj = User.objects.get(username = username)
    cart_obj = Cart.objects.filter(user__username = username)
        
    context = {
        "user_obj": user_obj,
        "user_form": user_form,
        "profile_form": profile_form,
        "cart_obj": cart_obj
    }
    if request.method == 'POST':
        profile_update_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_update_form.is_valid() and profile_form.is_valid():
            profile_update_form.save()
            profile_form.save()
            return render(request, 'profile.html', context)
    return render(request, 'profile.html', context)

# @login_required
# def update_profile(request):
#     if request.method == 'POST':
#         user_form = UserForm(request.POST, instance=request.user)
#         profile_form = ProfileForm(request.POST, instance=request.user.profile or None)
#         if user_form.is_valid() and profile_form.is_valid():
#             user_form.save()
#             profile_form.save()
#             return HttpResponseRedirect('/profile')

#     else:
#         user_form = UserForm(instance=request.user)
#         profile_form = ProfileForm(instance=request.user.profile)
#     return render(request, 'update_profile.html', {
#         'user_form': user_form,
#         'profile_form': profile_form
#     })
    #     "cart_obj": cart_obj,
    # }
    # return render(request, 'profile.html', context)


def cart_items(request):
    username = request.user.username
    cart_obj = Cart.objects.filter(user__username = username)
    
    if request.method =="POST":
        head_count = request.POST.get("head_count")
        tour_date = request.POST.get("tour_date")
        cart_id = request.POST.get("cart_id")
        cart_title = request.POST.get("cart_title")
        cart = get_object_or_404(Cart, id = cart_id)
        if cart_title != None:
            cart_id = request.POST.get("cart_id")
            cart = get_object_or_404(Cart, id = cart_id)
            cost = cart.tour.cost
            head_count = cart.head_count
            total_cost = cost*head_count
            context = {
                "cart":cart,
                "total_cost": total_cost
            }

            #request the PAYTM to transfer the amount after payment of user
            param_dict = {

                        'MID': Test_Merchant_ID,
                        'ORDER_ID': str(cart.id),
                        'TXN_AMOUNT': str(total_cost),
                        'CUST_ID': str(request.user.id),
                        'INDUSTRY_TYPE_ID': 'Retail',
                        'WEBSITE': 'WEBSTAGING',
                        'CHANNEL_ID': 'WEB',
                        'CALLBACK_URL':'http://127.0.0.1:8000/handlerequest'
                        
            }
            checksum = Checksum.generate_checksum(param_dict, Test_Merchant_Key)
            
            return render(request, 'paytm.html', {'param_dict': param_dict, 'checksum':checksum})
        
        cart = get_object_or_404(Cart, id=cart_id)
        cart.tour_date = tour_date
        cart.head_count = head_count
        cart.save()  
        messages.success(request,'Items added to cart')
       
        return redirect("/cart-items/")
         
    context = {
        "cart_obj": cart_obj,

    }
    return render(request, 'cart_items.html', context)


def select_tour(request, tour_id):
    tour = get_object_or_404(Tour, id=tour_id)
    context = {
        "tour":tour
    }
    return render(request, "add_to_cart.html", context)
    
@login_required
def add_to_cart(request, tour_id):
    if request.method =="POST":
        head_count = request.POST.get("head_count")
        tour_date = request.POST.get("tour_date")
        tour = get_object_or_404(Tour, id=tour_id)
        user = request.user
        cart = Cart.objects.create(head_count=head_count, tour_date=tour_date, user=user, tour=tour)
        cart.save()  
        messages.success(request,'Items added to cart')
        print(tour_date)
        return redirect('/cart-items/')
        # return redirect("/checkout/"+str(cart.id))
        # return redirect("/tour_id/"+str(tour_id))

    return render(request, 'add_to_cart.html')
    # return redirect(reverse('checkout'))

# @login_required
# def checkout(request, cart_id):
#     cart_id = int(cart_id)
#     cart = Cart.objects.get(id = cart_id)
#     cost = cart.tour.cost
#     head_count = cart.head_count
#     total_cost = cost*head_count
#     context = {
#         "cart":cart,
#         "total_cost": total_cost,
#     }
#     if request.method=="POST":
#         #request the PAYTM to transfer the amount after payment of user
#         param_dict = {
#             'MID': 'xyxyxyxyx',
#             'ORDER_ID': str(cart.id),
#             'TXN_AMOUNT': str(total_cost),
#             'CUST_ID': request.user.email,
#             'INDUSTRY_TYPE_ID': 'Retail',
#             'WEBSITE': 'DEFAULT',
#             'CHANNEL_ID': 'WEB',
#             'CALLBACK_URL':'http://127.0.0.1:8000/handlerequest',
#         }
#         param_dict['CHECKSUMHASH'] = Checksum.generate_checksum(param_dict, MERCHANT_KEY)
#         return render(request, 'paytm.html', {'param_dict': param_dict})
#     return render(request, 'checkout.html', context)


@csrf_exempt
def handlerequest(request):
    Test_Merchant_Key = config('Test_Merchant_Key')
    form = request.POST
    response_dict = {}
    for i in form.keys():
        response_dict[i] = form[i]
        if i == 'CHECKSUMHASH':
            checksum = form[i]
    verify = Checksum.verify_checksum(response_dict, Test_Merchant_Key, checksum)
    
    if verify:
        if response_dict['RESPCODE'] == '01':
            order_id  = response_dict['ORDERID']
            cart = Cart.objects.get(id = order_id)
            cart.sell_status = True
            cart.save()  
            
            # user_obj = request.user
            # name = user_obj.first_name
            # email = user_obj.email
            
            # booking_detali = str(name)+"\n"+"order id" +str(order_id)+"\n" +"no of person" + str(cart.head_count)+ "tour date"+ str(cart.tour_date) + "tour"+ str(tour+ cart.tour.place)
            
            # send_mail("booking details", booking_detali,"paul@polo.com", [email])
            
            # print(request.user.email)
            # print(request.user.username)
            
            print("ok")
        else:
            print("not ok")

mainapp/templates/booked_tours_detail.html
{{cart_obj.tour.country}}<br>
{{cart_obj.tour.place}}<br>
{{cart_obj.tour.tour_duration}}<br>
{{cart_obj.tour.title}}<br>
{{cart_obj.tour.description}}<br>
{{cart_obj.tour.image}}<br>
{{total_cost}}<br>
{{cart_obj.booking_date}}<br>
{{cart_obj.tour_date}}<br>

mainapp/templates/error_404.html
<h1>this is 404 page</h1>

mainapp/templates/error_500.html
<h1>this is 500 page</h1>

mainapp/templates/footer.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<footer class="page-footer font-small stylish-color-dark pt-4" style="background: black; color:white">
    <div class="container text-center text-md-left">
        <div class="row">
        <div class="col-md-4 mx-auto">
            <h5 class="font-weight-bold mt-3 mb-4"><a style="color: white;" href="{% url 'main:index' %}">BookMyTrips</a></h5>
            <p>
                We have activities across 17 countries, across every category so that you never miss best things to do anywhere.
            </p>
        </div>
        <hr class="clearfix w-100 d-md-none">
        <div class="col-md-2 mx-auto">
            <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Useful Links</h5>
            <ul class="list-unstyled" >
                <li>
                    <a style="color: white;" href="#!">Help</a>
                </li>
                <li>
                    <a style="color: white;" href="#!">Tourism</a>
                </li>
                <li>
                    <a style="color: white;" href="#!">Free Mobile App</a>
                </li>
            </ul>
        </div>
        <hr class="clearfix w-100 d-md-none">
        <div class="col-md-2 mx-auto">
            <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Communities</h5>
            <ul class="list-unstyled">
                <li>
                    <a style="color: white;" href="#!">Developers</a>
                </li>
                <li>
                    <a style="color: white;" href="#!">Brands</a>
                </li>
                <li>
                    <a style="color: white;" href="#!">Investors</a>
                </li>
                <li>
                    <a style="color: white;" href="#!">Vendors</a>
                </li>
            </ul>
        </div>
        <hr class="clearfix w-100 d-md-none">
        <div class="col-md-2 mx-auto">
            <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Company</h5>
            <ul class="list-unstyled">
            <li>
                <a style="color: white;" href="#!">About Us</a>
            </li>
            <li>
                <a style="color: white;" href="#!">Jobs</a>
            </li>
            <li>
                <a style="color: white;" href="#!">For The Record</a>
            </li>
            <li>
                <a style="color: white;" href="#!">We are hiring</a>
            </li>
            </ul>
        </div>
        </div>
    </div>
    <hr>
    <ul class="list-unstyled list-inline text-center py-2">
        <li class="list-inline-item">
        <h3 class="mb-1">BookMyTrips</h3>
        </li>
        
    </ul>
    <hr>
    <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
        <a style="color: white;" class="btn-floating btn-fb mx-1">
            <i class="fab fa-facebook-f"> </i>
        </a>
        </li>
        <li class="list-inline-item">
        <a style="color: white;" class="btn-floating btn-tw mx-1">
            <i class="fab fa-twitter"> </i>
        </a>
        </li>
        <li class="list-inline-item">
        <a style="color: white;" class="btn-floating btn-gplus mx-1">
            <i class="fab fa-google-plus-g"> </i>
        </a>
        </li>
        <li class="list-inline-item">
        <a style="color: white;" class="btn-floating btn-li mx-1">
            <i class="fab fa-linkedin-in"> </i>
        </a>
        </li>
        <li class="list-inline-item">
        <a style="color: white;" class="btn-floating btn-dribbble mx-1">
            <i class="fab fa-dribbble"> </i>
        </a>
        </li>
    </ul>
    <div class="footer-copyright text-center py-3">
    </div>
</footer> 

mainapp/templates/header.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand  text-white " href="{% url 'main:index' %}"><p>BookMyTrips</p></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end " id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" style="color: white;" href="#">Host a home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" style="color: white;" href="#">Host an experience</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" style="color: white;" href="#">Help</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" style="color: white;" href="#">|</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link active" style="color: white;" href="{% url 'account_logout' %}">Sign Out</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" style="color: white;" href="{% url 'main:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" style="color: white;" href="{% url 'main:cart_items' %}">Cart</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link active" style="color: white;" href="{% url 'account_login' %}">Sign In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: white;" href="{% url 'account_signup' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

mainapp/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Holiday Lets, Homes, Experiences &amp; Places - BookMyTrips</title>
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
</head>

<body>
    <div>
        <div class="header">
            {% include 'header.html' %}
            <div class="header-content">
                <div style="width: 50%;">
                    <div style="text-align:center;">
                        <h1>10,000+ Travel Experiences in 25+ Countries</h1>
                        <h3>BE THERE, DO THAT!</h3>
                    </div>
                    <div>
                        <form action="" method="POST">
                            {% csrf_token %} {{ form }}
                            <button class="btn btn-primary"  type="submit">Go</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="intro-container">
            <div class="intro-container-body">
                <div class="intro-container-element">
                    <div>
                        <img class="intro-container-image" src="https://colorlib.com/preview/theme/travello/images/beach.svg" alt="">
                    </div>
                    <div class="intro-container-text">
                        <p>
                            Top Destinations 
                        </p>
                        <p class="into-container-subtext">
                            10,000+ Travel Experiences in 25+ Countries
                        </p>
                    </div>
                </div>
                <div class="intro-container-element">
                    <div>
                        <img class="intro-container-image" src="https://colorlib.com/preview/theme/travello/images/wallet.svg" alt="">
                    </div>
                    <div  class="intro-container-text">
                        <p>
                            The Best Prices 
                        </p>
                        <p class="into-container-subtext">
                            Instant book with suppliers in real time
                        </p>
                    </div>
                </div>
                <div class="intro-container-element">
                    <div>
                        <img class="intro-container-image" src="https://colorlib.com/preview/theme/travello/images/suitcase.svg" alt="">
                    </div>
                    <div class="intro-container-text">
                        <p>
                            Amazing Services 
                        </p>
                        <p class="into-container-subtext">
                            With 98.7 CSAT we always exceed your expectations.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if search %}
        <div class="search-container">
            <div class="search-container-title">
                <div>
                    search result(s)
                </div>
            </div>
            <!-- ----------------------------------------------------------------------------------- -->
            <div class="search-container-items">
                <div class="search-result-items">
                    {% for s in search %}
                    <div class="card" style="width:33%;">
                        <img src="{{ s.image }}" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{ s.title }}</h5>
                            <p class="card-text">{{ s.cost }} <br>
                                <a href="/tour-id/{{s.id }}" class="btn btn-primary">Book Event</a>
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- ----------------------------------------------------------------------------------- -->
            </div> 
        </div>
    {% endif %}
    <div class="tour-container">
        <div>
            <div class="tour-container-title">
                simply amazing places
            </div>
            <div class="tour-container-main-title">
                <h2>Curated Travel Experiences Across The Globe</h2>
            </div>
        </div>
        <!-- ----------------------------------------------------------------------------------- -->
        <div class="tour-container-items">
            <div class="tour-result-items">
                {% for country in countries %}
                {% if country.name != 'India' %}
                <div class="card" style="width:33%;">
                    <img src="{{ country.image }}" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">{{ country.name }}</h5>
                        <!-- <p class="card-text">{{country}} <br> -->
                            <a href="{% url 'main:tourselect' country.id %}" class="btn btn-primary">Explore</a>
                        </p>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <!-- ----------------------------------------------------------------------------------- -->
        </div> 
    </div>

    <div>
        <div>
            <div class="tour-container-main-title">
                <h2 style="text-align: center;">Popular Tours </h2>
            </div>
        </div>
        <!-- ----------------------------------------------------------------------------------- -->
        <div class="tour-container-items">
            <div class="tour-result-items">
                {% for tour in popular_tours %}
                <div class="card" style="width:33%;">
                    <img src="{{ tour.image }}" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">{{ tour.title }}</h5>
                        <p class="card-text">{{ tour.cost }} <br>
                            <a href="/tour-id/{{tour.id }}" class="btn btn-primary">Book Event</a>
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- ----------------------------------------------------------------------------------- -->
        </div> 
    </div>

    {% include 'footer.html' %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

mainapp/templates/paymentstatus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>PayTm payment merchant</title>
</head>
<body>
    <div style="padding: 50px;">
        <h1>
            Payment status regarding your order Id {{response.ORDERID}}
        </h1>
    </div>
    <div class="container" style="color: black;">
        <table class="table table-hover table-dark">
            <tbody>
                <tr class="bg-info">
                    <td>ORDER ID</td>
                    <td>{{response.ORDERID}}</td>
                </tr>
                <tr class="bg-info">
                    <td>MID</td>
                    <td>{{response.ORDERID}}</td>
                </tr>
                <tr class="bg-info">
                    <td>Transection Amount</td>
                    <td>{{response.TXNAMOUNT}}</td>
                </tr>
                {% if response.RESPCODE == '01' %}
                <tr class="bg-info">
                    <td>Transection Status</td>
                    <td>Transection Successful</td>
                </tr>
                {% else %}
                <tr class="table-danger">
                    <td>Transection Status</td>
                    <td>Transection Failed</td>
                </tr>
                {% endif %}
                <tr class="bg-info">
                    <td>Message</td>
                    <td>{{response.RESPMSG}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div style="display: flex; justify-content:center;">
        <a style="border: 1px solid black" href="{% url 'main:index' %}">Go Home</a>
    </div>
</body>
</html>